/**
 * robots.txt — generated by Next.js from app/robots.ts.
 *
 * Allows all crawlers on all routes EXCEPT /gbp (noindex duplicate-content
 * avoidance) and /api/* (server endpoints).
 */

import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/gbp'],
      },
    ],
    sitemap: 'https://largolawn.pro/sitemap.xml',
  };
}
