/**
 * /hurricane-prep — Hurricane Prep & Cleanup deep-dive hub.
 *
 * Why this page exists separately from /services/hurricane-prep:
 *   - The /services/hurricane-prep page is the service card
 *     (ServiceHero + ServiceIncludes + ServiceBeforeAfter +
 *     ServiceFAQ + ServiceCTA). Its job is "buy this service."
 *   - The /hurricane-prep page is the editorial hub. Its job is
 *     "what to do before / during / after a named storm in
 *     Pinellas." The 96-hour timeline, the in-scope / not-in-scope
 *     clarity, the insurance paperwork help, and the longer Q&A
 *     live here. Both surfaces are valid destinations; the hub
 *     is preferred for the "hurricane prep Largo FL" / "post-storm
 *     yard cleanup 33771" search intents because the long-form
 *     content ranks for the long tail.
 *
 * Page composition (server-rendered, 7 sections):
 *   1. Page-level hero (eyebrow + h1 + tagline).
 *   2. The 96-hour timeline (cone watch → recovery).
 *   3. What's in scope (6 bullet points).
 *   4. What's NOT in scope (5 bullet points — arborist work, roof
 *      tarping, structural damage, inside-the-house, non-route).
 *   5. Insurance paperwork help (5 bullets).
 *   6. Hurricane FAQ (8 Q&As in a Radix accordion).
 *   7. Related links strip (service card, quote, contact, 33778
 *      area page, /faq).
 *
 * SEO:
 *   - Title: targets "Hurricane Prep Largo FL" + "Post-storm Yard
 *     Cleanup 33771"
 *   - JSON-LD: FAQPage (the 8 Q&As) + BreadcrumbList (Home > Hub)
 *   - Canonical: /hurricane-prep
 *   - OG: 1200x630 generated by apps/web/src/app/hurricane-prep/
 *     opengraph-image.tsx (separate route handler)
 *
 * Single source of truth: every block of copy comes from
 * `lib/content.ts → hurricanePrepPage`. Editing the timeline, the
 * scope list, the FAQ, etc. is one file edit.
 */

import { Container, Eyebrow, Section } from '@/components/site';
import { Accordion } from '@/components/ui';
import { BUSINESS } from '@/lib/business';
import { hurricanePrepPage } from '@/lib/content';
import { JsonLd, pageBreadcrumb } from '@/lib/json-ld';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Hurricane Prep + Post-Storm Cleanup in Largo, FL',
  description: `Pre-storm sweep, post-storm haul, and the insurance paperwork that goes with it. Pinellas County, June through November. From ${BUSINESS.name}, a solo-operator route in ${BUSINESS.address.city}, FL.`,
  alternates: { canonical: '/hurricane-prep' },
};

export default function HurricanePrepPage() {
  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: hurricanePrepPage.faqs.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: f.a,
      },
    })),
    provider: { '@type': 'LandscapingBusiness', name: BUSINESS.name },
  };

  const breadcrumbSchema = pageBreadcrumb({
    currentLabel: 'Hurricane prep + cleanup',
    currentHref: '/hurricane-prep',
  });

  return (
    <>
      <JsonLd data={faqJsonLd} />
      <JsonLd data={breadcrumbSchema} />

      {/* 1. Page hero */}
      <Section rhythm="loose">
        <Container size="prose">
          <Eyebrow tone="default">{hurricanePrepPage.eyebrow}</Eyebrow>
          <h1>{hurricanePrepPage.heading}</h1>
          <p>{hurricanePrepPage.tagline}</p>
        </Container>
      </Section>

      {/* 2. The 96-hour timeline. Each step is a <li> with the time
       * window as the headline + a 1-2 sentence body. The structure
       * is the same "window: T-minus / post-storm" cadence the
       * Pinellas County emergency management office uses, so the
       * page reads as familiar to anyone who has lived through a
       * storm. */}
      <Section>
        <Container size="prose">
          <h2>{hurricanePrepPage.timelineHeading}</h2>
          <p>{hurricanePrepPage.timelineIntro}</p>
          <ol>
            {hurricanePrepPage.timeline.map((step) => (
              <li key={step.window}>
                <p>
                  <strong>{step.window}: {step.title}</strong>
                </p>
                <p>{step.body}</p>
              </li>
            ))}
          </ol>
        </Container>
      </Section>

      {/* 3. What's in scope — 6 service items. The pre-storm sweep
       * bullets, the post-storm haul bullets, and the recovery
       * follow-up. This is the "yes we do this" list. */}
      <Section tone="soft">
        <Container size="prose">
          <h2>{hurricanePrepPage.scopeHeading}</h2>
          <ul>
            {hurricanePrepPage.scopeItems.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Container>
      </Section>

      {/* 4. What's NOT in scope — 5 explicit exclusions. The most-
       * important section of the page for trust. Most homeowners
       * do not know that standing-tree removal is licensed arborist
       * work (FL DEPCP certification), that roof tarping is a
       * licensed-contractor job, or that inside-the-house work is
       * outside any lawn-care operator's scope. Naming the
       * exclusions up front is the right call. */}
      <Section>
        <Container size="prose">
          <h2>{hurricanePrepPage.notInScopeHeading}</h2>
          <ul>
            {hurricanePrepPage.notInScopeItems.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Container>
      </Section>

      {/* 5. Insurance paperwork help — 5 bullets. The customer
       * needs to know what documentation they will get from the
       * operator to support the claim: invoice, photos, NHC
       * reference, volume estimate, and the licensed-and-insured
       * documentation caveat (deferred until GL binds per
       * state/ledger.yaml -> OBJ-M2-003). */}
      <Section tone="soft">
        <Container size="prose">
          <h2>{hurricanePrepPage.insuranceHeading}</h2>
          <p>{hurricanePrepPage.insuranceIntro}</p>
          <ul>
            {hurricanePrepPage.insuranceItems.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Container>
      </Section>

      {/* 6. FAQ — 8 Q&As. Same Accordion primitive the /faq page
       * uses. id="hurricane-prep-faq" so the disclosure widget's
       * DOM ids don't collide with the homepage / /faq surfaces. */}
      <Section>
        <Container size="prose">
          <h2>{hurricanePrepPage.faqHeading}</h2>
          <Accordion
            id="hurricane-prep-faq"
            items={hurricanePrepPage.faqs.map((f) => ({ q: f.q, a: <p>{f.a}</p> }))}
          />
        </Container>
      </Section>

      {/* 7. Related links — the natural next step. The service
       * card is the fast path for "I want to book"; the quote
       * form is the lead-capture for "I want to get on the prep
       * list"; the 33778 area page is the geographic anchor for
       * the most-exposed ZIP on the route. */}
      <Section tone="warm" rhythm="loose">
        <Container size="prose">
          <h2>{hurricanePrepPage.relatedHeading}</h2>
          <ul>
            {hurricanePrepPage.relatedLinks.map((link) => (
              <li key={link.href}>
                <a href={link.href}>
                  <strong>{link.label}</strong>
                </a>
                {' — '}
                {link.blurb}
              </li>
            ))}
          </ul>
          <p>
            Have a storm on the way?{' '}
            <a href={`tel:${BUSINESS.phoneTel}`}>{BUSINESS.phone}</a> or{' '}
            <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a>.
          </p>
        </Container>
      </Section>
    </>
  );
}
