/**
 * wf_nightly_kpi_snapshot.ts — Nightly KPI snapshot writer (stub).
 *
 * Phase 4-5 deliverable. When Inngest is wired, this runs on cron '0 2 * * *' ET.
 * Until then, the function is callable directly: `bun run workflows/wf_nightly_kpi_snapshot.ts`
 *
 * Reads all twin models via the platform packages and writes a snapshot per KPI
 * into state/kpi-snapshots/YYYY-MM-DD.yaml.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SNAPSHOT_DIR = 'state/kpi-snapshots';
const DATE = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

interface KpiSnapshot {
  kpi_key: string;
  actual: number;
  target: number;
  variance_pct: number;
  computed_at: string;
}

// Stub: in production, read from platform packages (database/stripe/postHog/etc.)
async function computeKpis(): Promise<KpiSnapshot[]> {
  // Phase 4-5: replace with real queries against twin models
  return [
    {
      kpi_key: 'active_recurring_customers',
      actual: 0,
      target: 25,
      variance_pct: -100,
      computed_at: new Date().toISOString(),
    },
    {
      kpi_key: 'gm_run_rate',
      actual: 0,
      target: 50000_00,
      variance_pct: -100,
      computed_at: new Date().toISOString(),
    },
    // ... remaining KPIs from analytics/kpi-taxonomy.md
  ];
}

async function main() {
  const kpis = await computeKpis();
  mkdirSync(SNAPSHOT_DIR, { recursive: true });
  const snapshotPath = join(SNAPSHOT_DIR, `${DATE}.yaml`);
  const yaml = [
    '# Auto-generated by workflows/wf_nightly_kpi_snapshot.ts',
    '# Do not edit by hand.',
    `last_updated: ${new Date().toISOString()}`,
    'kpis:',
    ...kpis.map((k) =>
      [
        `  - kpi_key: ${k.kpi_key}`,
        `    actual: ${k.actual}`,
        `    target: ${k.target}`,
        `    variance_pct: ${k.variance_pct.toFixed(2)}`,
        `    computed_at: ${k.computed_at}`,
      ].join('\n'),
    ),
  ].join('\n');
  writeFileSync(snapshotPath, yaml);
  console.log(`✓ wf_nightly_kpi_snapshot: wrote ${kpis.length} KPIs to ${snapshotPath}`);
}

if (import.meta.main) {
  main().catch((err) => {
    console.error('✗ wf_nightly_kpi_snapshot failed:', err);
    process.exit(1);
  });
}
